# Generated by Django 3.2.7 on 2021-10-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
    ]
